global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'yieldharvest-monitor'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # YieldHarvest Backend API
  - job_name: 'yieldharvest-backend'
    static_configs:
      - targets: ['backend:3001']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx Frontend
  - job_name: 'nginx'
    static_configs:
      - targets: ['frontend:80']
    scrape_interval: 30s
    metrics_path: /nginx_status

  # Node Exporter (if added)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Hedera Mirror Node (external monitoring)
  - job_name: 'hedera-mirror-node'
    static_configs:
      - targets: ['testnet.mirrornode.hedera.com:443']
    scrape_interval: 60s
    scheme: https
    metrics_path: /api/v1/accounts
    params:
      account.id: ['0.0.2']  # Treasury account as health check
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'up'
        target_label: 'service'
        replacement: 'hedera_mirror_node'

  # Custom application metrics
  - job_name: 'yieldharvest-custom'
    static_configs:
      - targets: ['backend:3001']
    scrape_interval: 15s
    metrics_path: /api/metrics
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: backend:3001

  # Health check endpoints
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'backend:3001'
        - 'frontend:80'
    scrape_interval: 30s
    metrics_path: /health
    honor_labels: true
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'up'
        target_label: 'check_type'
        replacement: 'health'

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint.com/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Remote read configuration
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint.com/api/v1/read"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"