global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts/alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'yieldharvest-api'
    static_configs:
      - targets: ['localhost:3001']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'yieldharvest-frontend'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['localhost:9187']
    scrape_interval: 15s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Hedera Mirror Node (external monitoring)
  - job_name: 'hedera-mirror-node'
    static_configs:
      - targets: ['testnet.mirrornode.hedera.com:443']
    scrape_interval: 60s
    scheme: https
    metrics_path: /api/v1/accounts
    params:
      account.id: ['0.0.2']  # Treasury account as health check
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'up'
        target_label: 'service'
        replacement: 'hedera_mirror_node'

  # Custom application metrics
  - job_name: 'yieldharvest-custom'
    static_configs:
      - targets: ['backend:3001']
    scrape_interval: 15s
    metrics_path: /api/metrics
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: backend:3001

  # Health check endpoints
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'backend:3001'
        - 'frontend:80'
    scrape_interval: 30s
    metrics_path: /health
    honor_labels: true
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'up'
        target_label: 'check_type'
        replacement: 'health'

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint.com/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Remote read configuration
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint.com/api/v1/read"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"